-- MySQL Script generated by MySQL Workbench
-- Tue Nov 16 20:35:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bda
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bda` ;

-- -----------------------------------------------------
-- Schema bda
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bda` DEFAULT CHARACTER SET utf8 ;
USE `bda` ;

-- -----------------------------------------------------
-- Table `bda`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`user` ;

CREATE TABLE IF NOT EXISTS `bda`.`user` (
  `user_id` VARCHAR(20) NOT NULL,
  `pwd` VARCHAR(20) NOT NULL,
  `user_name` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `auth` TINYINT(1) NOT NULL DEFAULT 0,
  `view_count` INT NOT NULL DEFAULT 5,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`delivery`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`delivery` ;

CREATE TABLE IF NOT EXISTS `bda`.`delivery` (
  `location_name` VARCHAR(10) NOT NULL,
  `district` VARCHAR(10) NULL,
  `latitude` DECIMAL(9,7) NOT NULL,
  `longtitude` DECIMAL(10,7) NOT NULL,
  PRIMARY KEY (`location_name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`menu` ;

CREATE TABLE IF NOT EXISTS `bda`.`menu` (
  `menu_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `category` VARCHAR(20) NULL,
  `menu_name` VARCHAR(255) NOT NULL,
  `price` INT NOT NULL,
  PRIMARY KEY (`menu_id`),
  INDEX `fk_menu_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_menu_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bda`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`order` ;

CREATE TABLE IF NOT EXISTS `bda`.`order` (
  `order_detail_id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `user_id` VARCHAR(20) NOT NULL,
  `menu_id` INT NOT NULL,
  `location_name` VARCHAR(10) NULL,
  `datetime` DATETIME NOT NULL,
  `total` INT NOT NULL,
  `count` INT NULL,
  PRIMARY KEY (`order_detail_id`),
  INDEX `fk_order_user1_idx` (`user_id` ASC),
  INDEX `fk_order_delivery1_idx` (`location_name` ASC),
  INDEX `fk_order_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_order_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bda`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_delivery1`
    FOREIGN KEY (`location_name`)
    REFERENCES `bda`.`delivery` (`location_name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `bda`.`menu` (`menu_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`payment` ;

CREATE TABLE IF NOT EXISTS `bda`.`payment` (
  `payment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(20) NOT NULL,
  `payment_date` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`, `user_id`),
  INDEX `fk_payment_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_payment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bda`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -- -----------------------------------------------------
-- -- Table `bda`.`order_detail`
-- -- -----------------------------------------------------
-- DROP TABLE IF EXISTS `bda`.`order_detail` ;

-- CREATE TABLE IF NOT EXISTS `bda`.`order_detail` (
--   `order_detail_id` INT NOT NULL AUTO_INCREMENT,
--   `menu_id` INT NOT NULL,
--   `order_id` INT NOT NULL,
--   `count` INT NOT NULL,
--   PRIMARY KEY (`order_detail_id`),
--   INDEX `fk_order_detail_order1_idx` (`order_id` ASC),
--   INDEX `fk_order_detail_menu1_idx` (`menu_id` ASC),
--   CONSTRAINT `fk_order_detail_order1`
--     FOREIGN KEY (`order_id`)
--     REFERENCES `bda`.`order` (`order_detail_id`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION,
--   CONSTRAINT `fk_order_detail_menu1`
--     FOREIGN KEY (`menu_id`)
--     REFERENCES `bda`.`menu` (`menu_id`)
--     ON DELETE NO ACTION
--     ON UPDATE NO ACTION)
-- ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`time`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`time` ;

CREATE TABLE IF NOT EXISTS `bda`.`time` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_detail_id` INT NOT NULL,
  `time_zone` CHAR(1) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_time_order1_idx` (`order_detail_id` ASC),
  CONSTRAINT `fk_time_order1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `bda`.`order` (`order_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`season`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`season` ;

CREATE TABLE IF NOT EXISTS `bda`.`season` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_detail_id` INT NOT NULL,
  `season` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_season_order1_idx` (`order_detail_id` ASC),
  CONSTRAINT `fk_season_order1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `bda`.`order` (`order_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`date`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`date` ;

CREATE TABLE IF NOT EXISTS `bda`.`date` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_detail_id` INT NOT NULL,
  `day_of_week` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_date_order1_idx` (`order_detail_id` ASC),
  CONSTRAINT `fk_date_order1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `bda`.`order` (`order_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bda`.`years`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bda`.`years` ;

CREATE TABLE IF NOT EXISTS `bda`.`years` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `year` INT NOT NULL,
  `order_detail_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_years_order1_idx` (`order_detail_id` ASC),
  CONSTRAINT `fk_years_order1`
    FOREIGN KEY (`order_detail_id`)
    REFERENCES `bda`.`order` (`order_detail_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
